spring.application.name=toka-arena-backend
spring.datasource.url=${MYSQL_URL}
spring.datasource.username=${MYSQLUSER}
spring.datasource.password=${MYSQLPASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
talentland.api.base-url=https://talentland-toka.eastus2.cloudapp.azure.com
talentland.api.app-id=3500020265523984
talentland.api.alipay-merchant-code=${TALENTLAND_ALIPAY_MERCHANT_CODE}
toka.jwt.secret=${JWT_SECRET}
toka.jwt.expirationMs=86400000
server.port=${PORT:8080}
